name: Simulate GoogleChat Notif

on: workflow_dispatch

jobs:
  main:
    runs-on: windows-latest
    name: Build simulation
    
    steps:
      - name: build
        # simulate failure
        run: exit 1 
      
      - name: notify
        shell: powershell
        if: failure()
        run: |
          $workflowUrl='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          $title='${{ github.workflow }} *${{ job.status }}* on repo ${{ github.repository }}'
          $body = @{
            text = "$title\n<$workflowUrl|pipeline log>."
          }
          $body | ConvertTo-Json -Compress
          $body | ConvertTo-Json -Compress | curl.exe -sSLfv -o nul -X POST --url '${{ secrets.NB_FAILURES_WEBHOOK }}' --data-raw "@-"
