name: Simulate GoogleChat Notif

on: workflow_dispatch

jobs:
  main:
    runs-on: windows-latest
    name: Build simulation
    
    steps:
      - name: build
        # simulate failure
        run: exit 1 
      
      - name: notify
        if: failure()
        run: |
          $body=@"
          { "text": "${{ github.workflow }} *${{ job.status }}* on repo ${{ github.repository }}\nSee <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|pipeline log>." }
          "@
          echo "$body" | 
          curl -sSLf -o nul -X POST --url '${{ secrets.NB_FAILURES_WEBHOOK }}' --data-raw @-
