on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  xygeni-scan:
    runs-on: ubuntu-latest
    name: xygeni-github-action
    steps:
      # Checkout repo (into GITHUB_WORKSPACE)
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Download
        shell: bash
        run: |
          # curl -s -o ${{ runner.temp }}/xygeni_scanner.zip -H "Authorization: Bearer ${{ secrets.XYGENI_TOKEN }}" -L ${{ vars.XYGENI_URL }}/scan/releases
          curl -s -o ${{ runner.temp }}/xygeni_scanner.zip -L https://92f0-46-24-156-184.ngrok-free.app/xygeni-release.zip
          cd ${{ runner.temp }}
          unzip ${{ runner.temp }}/xygeni_scanner.zip
          rm ${{ runner.temp }}/xygeni_scanner.zip

      #- name: Run secrets scan
      #  shell: bash
      #  run: >
      #    ${{ runner.temp }}/xygeni_scanner/xygeni
      #    --token="${{ secrets.XYGENI_TOKEN }}" --url="${{ vars.XYGENI_URL }}"
      #    secrets
      #    --name="${{ github.repository }}" --dir="${{ github.workspace }}" --no-stdin
      #    --format=sarif --output="${{ runner.temp }}/reports/secrets.sarif"
      #    --fail-on=never
      #  env:
      #    API_KEY: ${{ secrets.XYGENI_TOKEN }}

      - name: Run full scan
        shell: bash
        run: >
          ${{ runner.temp }}/xygeni_scanner/xygeni 
          --token="${{ secrets.XYGENI_TOKEN }}" --url="${{ vars.XYGENI_URL }}" 
          scan --run=suspectdeps,secrets,misconf,iac,compliance 
          --name="${{ github.repository }}" --dir="${{ github.workspace }}"
          --standard=cis_sscs
          --send-to=github
          --fail-on=never --no-upload --try-all-scans
        env:
          API_KEY: ${{ secrets.XYGENI_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}

      #- name: Xygeni-Scanner
      #  uses: xygeni/xygeni-action@v2.1
      #  id: Xygeni-Scanner
      #  env:
      #    XYGENI_SERVER:
      #    XYGENI_TOKEN: ${{ secrets.XYGENI_TOKEN }}
      #  with:
      #    # https://apidev.xygeni.io/deps-doctor-service
      #    xygeni_url: ${{ vars.XYGENI_URL }}
      #    token: ${{ secrets.XYGENI_TOKEN }}
      #    gh_token: ${{ github.token }}
      #    command: >-
      #      -q secrets -n ${{ github.repository }} -d ${{ github.workspace }}
      #        --format sarif --output ${{ github.workspace }}/secrets.sarif

      #- name: Upload SARIF report
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
          # Path to SARIF file relative to the root of the repository
      #    sarif_file: ${{ runner.temp }}/reports
          # Optional category for the results
          # Used to differentiate multiple results for one commit
      #    category: xygeni-secrets


