on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  xygeni-scan:
    runs-on: ubuntu-latest
    name: xygeni-github-action
    steps:
      # Checkout repo (into GITHUB_WORKSPACE)
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Xygeni-Scanner
        uses: xygeni/xygeni-action@v2.1
        id: Xygeni-Scanner
        with:
          token: ${{ secrets.XYGENI_TOKEN }}
          command: >-
            -q secrets -n ${{ github.repository }} -d ${{ github.workspace }}
              --format sarif --output ${{ github.workspace }}/secrets.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: secrets.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: xygeni-secrets

